### ISSUE TITLE
KeePass.config.xml Backup

### ISSUE THREAD

**Issue by Wild13c** [marvinweber/KPSimpleBackup#16]
Hi Marvin,  I wanted to see if you could possibly add the capability of backing up the KeePass.config.xml along with the database file.  My idea would be using a check box to be able to select the KeePass.config.xml file to be backed up with the database file.

The reason for this request is that the KeePass.config.xml has all of the current window layout and formatting in it so when you replace both the database file and the KeePass.config.xml files for a new version of keepass you have the same layout without the hassle of resizing etc.

Thanks for your consideration,

**Comment by marvinweber** [comment]
Sounds interesting, i'll mark it as feature request and will have a look at it...

**Comment by marvinweber** [comment]
**FYI**: Starting with the next release of KPSimpleBackup ([Version 1.3](https://github.com/marvinweber/KPSimpleBackup/milestone/1)) you can enable the "Backup KeePass config option" in the settings. Note that it is still labeled as _BETA_, since it is not working properly with the portable version of KeePass yet.

**Comment by Wild13c** [comment]
Marvin,
I will give it a try.  Thanks for adding the KeePass.config.xml feature.
