### ISSUE TITLE
Refine and increase options for triggering a backup

### ISSUE THREAD

**Issue by wellread1** [marvinweber/KPSimpleBackup#24]
Thanks for the very nice plugin.

I use the long term backup feature provided by KPSimpleBackup but rely on KeePass synchronization to a cloud drive for "continuous" backup.  I would prefer to avoid the extra overhead incurred by the Simple Backup that occurs with each KeePass save event, and would rather defer these backups to a more convenient time, such as when KeePass has been inactive for a while.  

Would it be possible to:

* Provide an option to disable backup on saving in favor of the existing backup on database closing option?  
* Add an option for periodic backup when KeePass has been inactive for a specified period?
* Keep track of "database has unsaved changes" since a backup so deferred backups (periodic, or on db closing) would be made only when the database has changed since the last backup.

**Comment by marvinweber** [comment]
Thx for your feedback, so regarding your points:

- You can disable performing backups on every save (**Advanced** -> **General Backup Options** -> **Auto Backup Database**)  
instead you can enable making backups if keepass or the database is closed (**Advanced** -> **Advanced Backup Options** -> **Backup database whent it's...**
- I think with the current implementation of the plugin this is not possible, since your database probably get's locked after some time of inactivity.  
I'll check if it is possible somehow, but I don't think so...  
"Backups on close" as described above is no suitable solution for you?
- This is probably possible, I'll try to look into it :)

**Comment by wellread1** [comment]
Thanks!  Argh! I did not notice the option to disable the auto-backup.  Backup on close will work nicely for me.

FYI: A "Time-Periodic" event is exposed in the trigger system.  The interval can be set in this event to a value shorter than the KeePass locking interval.  Though I am not a developer, the existence of this event in the trigger system seems to imply the event will also accessible to plugins.

**Comment by jon-f-novastor** [comment]
Note, at least in my testing using the latest release versions of KPSimpleBackup 1.3 and KeePass 2.4.5, the existing option that was discussed "Advanced -> Advanced Backup Options -> Backup database when it's..." when that option is disabled (unchecked) it also saves the database on Workspace Lock or auto-lock workspace when it hits X timeout.  It does not say it will do that in the option description text but it does do that in my testing today and it does not seem to matter the other combination of options utilized both in Keepass 2.4.5 and in KPSimpleBackup.  The option we are talking about when disabled is:

![image](https://user-images.githubusercontent.com/50121594/91603707-560bdf80-e922-11ea-9320-70e5ac441435.png)

I reported that issue today as a new issue: https://github.com/marvinweber/KPSimpleBackup/issues/26.

So with this option unchecked it still may bother some (as it has to wait in my case about 45 seconds) to do all of the saves to multiple backup locations including two cloud locations, including Long Term Backup saves, each time the auto-workspace lock is triggered by the timer in KeePass, so it has to sit there saving all of those databases at that point each time it locks, which means you cannot get quickly back in to untray the application while it is doing that.  As suggested by wellread1 it would be a great thing to be able to have a new option that allows a time-periodic type of save whereby it calls the "Backup Database now!" function after a set number of idle time in minutes is reached.

**Comment by marvinweber** [comment]
A new backup for the option "Backup on Database Close" will now only be created when the database has been changed (even if you change the database, save it, and then close it -> this will still trigger a backup; meaning you can disable the "Auto-Backup on Save" and enable "Backup on Close" and still, a backup will be created everytime you change your database - when you close it).  
This will be included in the upcoming [Version 1.4](https://github.com/marvinweber/KPSimpleBackup/milestone/2).

However, I decided against a periodic backup trigger/interval, as I don't see the benefit: If you backup everytime you save, you don't need any further periodic backups. If you backup on close, you also make a backup when the database has been modified (assuming that you use a reasonable lock-interval, the risk of missing a backup due to a crash or similar is rather low. To minimize this risk, you should let the backups run when you save the database, anyway.

**Comment by marvinweber** [comment]
@jon-f-novastor 

> **it still saves the database when the workspace is locked**, whether if manual lock or when auto lock trigger is hit

Yes, this correct. The option you mentioned creates backups when you close or lock your database, or when KeePass is closed (as this closes the database, as well).  
The description of that option wasn't very good, I aggree :( I updated them to be more precise and will also update the descriptions in the Wiki to explain that in more detail.

---

> In this case it has to sit there saving all of the databases each time the workspace locks, in my case that is 45 seconds in total

Regarding the performance issues with the long-term-backups: This will be addressed in this ticket: #28

**Comment by jon-f-novastor** [comment]
Thanks, your resolve for issue #[24](https://github.com/marvinweber/KPSimpleBackup/issues/24) as to no longer trigger the save if nothing was modified, was the main issue I had in regards to save DB on close/lock/exit, which was the reason for my follow-up comment, as even if nothing was modified in the database it was adding 22 seconds (using v1.3, two destinations and LTB enabled, I believe in that case it was triggering many individual save operations) every time it either reached the lock database trigger or if the app was exited.  That is why I had the save on lock or close option disabled in v1.3 until v1.4 was released.  Note: For me as tested today the time it takes to lock the database is still 22 seconds in KPSimpleBackup v1.4, as it was in v1.3.
