### ISSUE TITLE
Every save triggers 4 consecutive saving processes

### ISSUE THREAD

**Issue by stonecrusher** [marvinweber/KPSimpleBackup#27]
Hi  
If I save the database, instead of 1 second it takes four times the amount as the process bar goes from 0% to 100% four times instead of one.
That's quite annoying.
I could lower the number of key transformation iterations as a workaround, but still I want to know why it does that.

![2020-09-11 16_44_52-Settings](https://user-images.githubusercontent.com/1388389/92939515-2eeafd00-f44e-11ea-9113-20e979c0d479.png)
![2020-09-11 16_45_02-Settings](https://user-images.githubusercontent.com/1388389/92939520-2f839380-f44e-11ea-93cf-f684c6e50b01.png)

KeePass 2.46
KPSimpleBackup 1.3.0
Intel Core i5-9300H (4 cores / 8 threads)
Win10 home x64 v1909

Thanks,
Stonecrusher

**Comment by marvinweber** [comment]
The KPSimpleBackup plugin used the built-in "save-feature" of KeePass for databases. If you've enabled Long-Term-Backups, KeePass has to save your database four times. Thats why you see the progress bar four times, which is - even though it might be annoying - expected behaviour. I don't know of any way to overwrite the progress-bar indicator to only go once from 0 to 100 % while KeePass is saving the Database four times :/

**Comment by stonecrusher** [comment]
Hmm, I didn't expect the L-T-B to resave e.g. the yearly backup on every little change.
Personally I don't even expect the long time stuff to be up to date.
A monthly backup should contain the last status of the past month, not the current month.
I don't need a yearly backup from 2020 because 2020 is not over yet and I have loads of more recent backups.

You get the point? So the saving strategy imho might need an overhaul.
Nonetheless, great plugin!

**Comment by marvinweber** [comment]
The concept of ltb backups is to provide a latest yearly, monthly and weekly version. So I actually want to have the latest version of 2020 in my ltb yearly folder (so that it is the latest 2020 version, if 2020 is over).  
But I also actually have an idea, how to speed up the saving process, if ltb is enabled (I'll open a new ticket for that).  
I additionally will check, whether it's possible to trigger the ltb backup only, if KeePass and/ or the database get's closed, which would not lead to multiple saving-events, unless the application is closed.

**Comment by marvinweber** [comment]
FYI, here are the new issues:

- Speed-Up saving: #28 
- New option to trigger LTB only on close: #29

Btw, as a workaround in the meantime, you can disable backups on every save and enable them on closing (second option under _Advanced Backup Options_). This will stop backups up on every save but only, if the Database gets closed.
