### ISSUE TITLE
Single DB with multiple PC/clients

### ISSUE THREAD

**Issue by rahul-ve** [marvinweber/KPSimpleBackup#44]
Thanks for the excellent plugin. 
I use a single DB (on my desktop) and access the same DB over the home network from my laptop. 
Keepass v2 allows for this use case out of the box but I had a DB corruption recently and I suspect this is due to my laptop not closing the DB cleanly.  I ended up setting up KPS on the desktop as a consequence to avoid any potential data loss. 

I haven't accessed the DB from laptop yet, and was wondering what will happen if I access it from my laptop and add a new entry, will it trigger the KPS backup process on the desktop when the DB syncs up?

Thanks
Rahul

**Comment by marvinweber** [comment]
Hey Rahul,

first of all, backups are only performed on KeePass installations with the KPSimpleBackup plugin installed (and set up). When a bakup is performed, depends on your settings. Depending on your settings in the "Advanced" Tab of the settings your db is backed up whenever you save (actively) the db, when KeePass is closed, or in both cases. Simply opening a modified (on a different device) database will currently not trigger a backup (however, sounds like a cool new feature btw ;)).  
Checkout the Wiki for more information (also, i am working on better and clearer docs for Version 2.0).

Hope this helped, otherwise feel free to reopen the issue again :)
