### ISSUE TITLE
Deletes the orignal kdb files when maxim # of backup is reached

### ISSUE THREAD

**Issue by SvenBent** [marvinweber/KPSimpleBackup#5]
If you decided to use the folder of the orignal .kdbx file as backup folder as well, then KPsimpelBackup will deletet the original .kdbx file when reaching maximum number of backups.

This make keepas not able to find its database at next startup and is a most unwanted behavioer.
KpsimpleBackup shoulder never delete the original database file.

aka
Original database: C:\KeePass\Database.kdbx
Backups folder: C:\KeePass\
once maximum numbers of backups are hit. It Deletes Database.kdbx rather than one of the backup files

**Comment by weberonede** [comment]
You are right, that should not happen. I will have a look at it, thanks for reporting this issue :)

**Comment by SvenBent** [comment]
Hi
This sounds Awesome I will be awaiting  the update.
This is on of my recommende plugin Because it so easy to set up and yet such a big importance.

I would however give a suggestion
a separate line of backups that only save if its a new week or month
So you would have the normal 20  backups tha is everytime you save.
but also lets say 4 that each is one week/month in between.
This would help agiant saturating the normal number of backups during  time with a lot of changes and then suddenly realise you delete once a bit earlier.

Example
Database_Week05
Database_Week06
Database_Week07
Databsae_Week08

Anyway once again thank you for the plugin

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by micaelvaleri** [comment]
I can't find any way to check the full path

![image](https://user-images.githubusercontent.com/54272511/64181116-84361b00-ce98-11e9-96c3-bf8d3f7dd620.png)

also for some reason 3 days ago it stopped doing the backups. A log file somewhere would be very useful in these cases. Maybe an idea for the next release :)

**Comment by marvinweber** [comment]
I fixed this issue (see 68f1f27fd6e8585e575b70d6274c25a13d70edb9), the fix will be included in the next update (which will be released today :))

> This is on of my recommende plugin Because it so easy to set up and yet such a big importance.

Glad to hear that! 😄 

---

> I would however give a suggestion
a separate line of backups that only save if its a new week or month
So you would have the normal 20  backups tha is everytime you save.
but also lets say 4 that each is one week/month in between.
This would help agiant saturating the normal number of backups during  time with a lot of changes and then suddenly realise you delete once a bit earlier.

That sounds interesting. I'll open a new ticket for that so that we can close this bug ticket :)
Thx for this recommendation, I try to implement it as soon as possible ;)
