### ISSUE TITLE
Path field too short

### ISSUE THREAD

**Issue by micaelvaleri** [marvinweber/KPSimpleBackup#6]
I can't find any way to check the full path

![image](https://user-images.githubusercontent.com/54272511/64181306-ce1f0100-ce98-11e9-97d7-a2f1dca4c862.png)

also for some reason 3 days ago it stopped doing the backups. A log file somewhere would be very useful in these cases. Maybe an idea for the next release :)

**Comment by micaelvaleri** [comment]
I deleted the two older copies and it did work.. Maybe some issue enumerating the existing copies under certain conditions?

**Comment by weberonede** [comment]
I will add a tooltip that will enable you to see the full path.

To the second problem: I need some more information about your "setup" to figure out the problem. What I see from your screenshot is, that the date format is set to `ddMMyyyy` which results in the same filename as long as it's the same day (because hours, minutes and seconds are not covered in the name). Could that be the problem in your case? So that it just overwrites an already existing backup from the same day?

**Comment by micaelvaleri** [comment]
Machine is a Win 8.1 Pro and the kdbx is in OneDrive, the target folder for the backup instead is in the local drive.
I get your point, I thought that too but last backup was 31082019 and yesterday was 03092019 so no, the file name was not same.
When it worked I tried and, indeed, it appears it doesn't do another backup the same day. Which is fair.
Anyway, hopefully was a temporary problem. If it happens again I'll let you know.
And thanks for add-on, really simple and useful

**Comment by marvinweber** [comment]
I will have a look if I find something that could cause this problem :)
If you run into this issue again, please open another issue 👍 

The problem with the not readable path will be fixed in the next update :) (see bac0ca0cca119ff93475bb0354162ba22cceab11)
